// src/native/reconstruct.ts — spec 27 §L8: rebuildable-project emit
// including the native side, over the ALREADY-materialised `native/*.jsonl`
// tables in a project directory (L1/L2/L4/L6 — this module re-derives
// nothing from bytes, exactly like `seams.ts`/`native-deps.ts`, `source:
// "join"` in spirit). Three outputs, all bounded by the truth rule (spec 27
// §1.4 / §4.2 — a value is never fabricated):
//   1. `.env` from `native/env.jsonl` — recovered values only; an
//      `unresolved` key is a commented TODO carrying its evidence.
//   2. `package.json` native dependencies — the L7 merge
//      (`buildNativeChannel`) of `native/react-modules.jsonl` against
//      whatever `dependencies` the JS-fingerprint channel already wrote —
//      third-party libs only, each exactly once.
//   3. `native-todo/<Module>/` — one stub per FIRST-PARTY module
//      (`firstParty:true`): a faithful Java interface skeleton (signatures
//      only) plus a `RESYNTHESIZE.md` naming what is known and what is not.
//      No method body is ever fabricated.
//
// A project directory with no `native/` tables at all is a silent no-op
// (spec 27 §1.4 "native is optional-by-construction") — `reconstructNativeProject`
// returns `{ran:false, ...}` and writes nothing.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { packageOfDescriptor, typeDescriptorOfKey } from "./classify-party.ts";
import { buildNativeChannel } from "./native-deps.ts";
import type { NativeChannelReport } from "./native-deps.ts";
import { parseNativeJsonl } from "./schema.ts";
import type { EnvRow, NativeMethodRow, NativeModuleRow } from "./schema.ts";

/** Read one `<outDir>/native/<file>.jsonl` table, `[]` when absent — the
 *  same "absence is a fact, not an error" idiom as
 *  `ArtifactService.readNativeJsonl` (`src/artifact/service.ts`), duplicated
 *  rather than imported: that class also owns caching/CAPS-bounding this
 *  module has no use for. */
function readNativeTable<T>(outDir: string, file: string): readonly T[] {
  const path = join(outDir, "native", file);
  if (!existsSync(path)) return [];
  return parseNativeJsonl(readFileSync(path, "utf8")).rows as T[];
}

/** True when `<outDir>/native/` holds at least the two tables this module
 *  reads (§L8 "when the project directory has native tables"). A directory
 *  with `native/` present but e.g. only `classes.jsonl` (an ingest that
 *  found no react-modules) still counts — L8 has legitimate, if smaller,
 *  work to do (an `.env` from `env.jsonl` alone). */
function hasNativeTables(outDir: string): boolean {
  return existsSync(join(outDir, "native", "env.jsonl")) || existsSync(join(outDir, "native", "react-modules.jsonl"));
}

// --- 1. `.env` ---------------------------------------------------------

/** A value needs quoting when it is empty or carries whitespace, `#`, or a
 *  quote — anything else is written bare (the common `.env` convention). */
function envValueLiteral(value: string): string {
  if (value.length === 0 || /[\s"#]/.test(value)) return JSON.stringify(value);
  return value;
}

/** Render `native/env.jsonl` rows as `.env` text (spec 27 §L8 test 1/2):
 *  a recovered row is a plain `KEY=value` line; an `unresolved` row is a
 *  commented TODO citing its evidence (`source`/`resolvedBy`/the key itself
 *  — the field/class fact spec 27 §L8 names) — never a fabricated value.
 *  Pure: same rows, same text (spec 27 §4.1). */
export function renderEnvFile(rows: readonly EnvRow[]): string {
  const lines: string[] = [
    "# Generated by hbc2js native reconstruction (spec 27 L8) from native/env.jsonl.",
    "# Recovered values only -- an unresolved key is a commented TODO citing its evidence, never a fabricated value.",
  ];
  for (const r of rows) {
    if (r.value === "unresolved") {
      lines.push(`# TODO: ${r.key} -- unresolved (source: ${r.source}, field: ${r.key}, resolvedBy: ${r.resolvedBy})`);
    } else {
      lines.push(`${r.key}=${envValueLiteral(r.value)}`);
    }
  }
  return lines.join("\n") + "\n";
}

// --- 2. `package.json` native dependencies ------------------------------

/** Merge the L7 native dependency channel into an existing `dependencies`
 *  map: every merged dep exactly once, never overwriting a version the
 *  JS-fingerprint channel already wrote (§L8 test 4). Pure. */
export function mergeNativeDependencies(existingDependencies: Readonly<Record<string, string>>, nativeChannel: NativeChannelReport | null): Record<string, string> {
  const deps: Record<string, string> = { ...existingDependencies };
  if (nativeChannel === null) return deps;
  for (const d of nativeChannel.deps) {
    if (!(d.package in deps)) deps[d.package] = "*"; // native side has no version to offer, ever (never guessed)
  }
  return deps;
}

// --- 3. `native-todo/<Module>/` -----------------------------------------

const JAVA_PRIMITIVES: Record<string, string> = { V: "void", Z: "boolean", B: "byte", C: "char", S: "short", I: "int", J: "long", F: "float", D: "double" };

/** A JVM field/return type descriptor (`Ljava/lang/String;`, `I`, `[J`) ->
 *  a readable, fully-qualified Java type name. A shape this does not
 *  recognise is echoed back verbatim (never guessed). */
export function javaTypeName(descriptor: string): string {
  let d = descriptor;
  let arraySuffix = "";
  while (d.startsWith("[")) {
    d = d.slice(1);
    arraySuffix += "[]";
  }
  const prim = JAVA_PRIMITIVES[d];
  if (prim !== undefined) return prim + arraySuffix;
  const m = /^L(.+);$/.exec(d);
  if (m !== null) return m[1]!.split("/").join(".") + arraySuffix;
  return d + arraySuffix;
}

/** Split a JVM parameter-descriptor string (the inside of a proto's `(...)`)
 *  into its individual type descriptors — array/object descriptors span more
 *  than one character, so this cannot be a plain character split. */
function splitDescriptors(s: string): string[] {
  const out: string[] = [];
  let i = 0;
  while (i < s.length) {
    const start = i;
    while (s[i] === "[") i++;
    if (s[i] === "L") i = s.indexOf(";", i) + 1;
    else i++;
    out.push(s.slice(start, i));
  }
  return out;
}

/** `(Ljava/lang/String;I)V` -> its parameter descriptors + return
 *  descriptor. A proto this does not parse yields `{params:[], returnType:
 *  "?"}` — an honest "unresolved", never a guess. */
export function parseJavaProto(proto: string): { readonly params: readonly string[]; readonly returnType: string } {
  const m = /^\(([^)]*)\)(.+)$/.exec(proto);
  if (m === null) return { params: [], returnType: "?" };
  return { params: splitDescriptors(m[1]!), returnType: m[2]! };
}

/** `native:method:Lcom/x/Foo;->bar(I)V` -> `(I)V` (the proto suffix after
 *  the last `->`), independent of `methods.jsonl` being present — the proto
 *  is already encoded in the key itself (`src/name-overlay/id.ts`'s
 *  `nativeMethodKey`). Falls back to `methods` when the key does not carry
 *  a recognisable proto shape (e.g. a future id encoding). */
function protoOfMethodKey(nativeMethodKey: string, methods: ReadonlyMap<string, NativeMethodRow>): string | null {
  const m = /->[^(]*(\(.*\))$/.exec(nativeMethodKey);
  if (m !== null) return m[1]!;
  return methods.get(nativeMethodKey)?.proto ?? null;
}

/** `Lcom/x/Foo;` -> `Foo`. */
function simpleClassName(descriptor: string): string {
  const m = /([^/;]+);$/.exec(descriptor);
  return m !== null ? m[1]! : descriptor;
}

/** The stub's file-safe name: the recovered JS name when there is one, else
 *  the implementing class's simple name — never `implClass` verbatim (a
 *  `native:type:...;` key is not a filesystem-safe name). */
function moduleStubName(row: NativeModuleRow): string {
  if (row.jsName !== null) return row.jsName;
  const descriptor = typeDescriptorOfKey(row.implClass);
  return simpleClassName(descriptor ?? row.implClass);
}

/** A faithful Java interface skeleton for one first-party module: real
 *  package, real class name, real method signatures — every body is a
 *  `TODO RESYNTHESIZE` that throws, never a fabricated implementation (spec
 *  27 §L8 test 3). Pure. */
export function renderModuleStub(row: NativeModuleRow, methods: ReadonlyMap<string, NativeMethodRow>): string {
  const descriptor = typeDescriptorOfKey(row.implClass) ?? row.implClass;
  const pkg = packageOfDescriptor(descriptor);
  const className = simpleClassName(descriptor);
  const lines: string[] = [
    "// AUTO-GENERATED by hbc2js native reconstruction (spec 27 L8).",
    "// Interface skeleton only: signatures are recovered facts, every method body below is a TODO -- no body is fabricated.",
  ];
  if (pkg !== null && pkg !== "") lines.push(`package ${pkg};`);
  lines.push("");
  lines.push(`public class ${className} /* ${row.kind} module${row.jsName !== null ? ` "${row.jsName}"` : " (name unresolved)"} */ {`);
  for (const m of row.methods) {
    const proto = protoOfMethodKey(m.nativeMethod, methods);
    const parsed = proto !== null ? parseJavaProto(proto) : { params: [], returnType: "?" };
    const params = parsed.params.map((p, i) => `${javaTypeName(p)} arg${i}`).join(", ");
    lines.push(`  public ${javaTypeName(parsed.returnType)} ${m.jsName}(${params}) {`);
    lines.push(`    // TODO RESYNTHESIZE: method body not recoverable from bytecode analysis (see RESYNTHESIZE.md).`);
    lines.push(`    throw new UnsupportedOperationException("TODO RESYNTHESIZE: ${className}.${m.jsName}");`);
    lines.push(`  }`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

/** `RESYNTHESIZE.md` for one first-party module: what is known (the
 *  exported `@ReactMethod` surface + any recovered string constants) and
 *  what is not (every method body) — spec 27 §L8's "honest gap" made
 *  concrete. Pure. */
export function renderResynthesizeMd(row: NativeModuleRow, methods: ReadonlyMap<string, NativeMethodRow>): string {
  const lines: string[] = [`# RESYNTHESIZE: ${row.jsName ?? row.implClass}`, ""];
  lines.push("Recovered from bytecode analysis by hbc2js (spec 27 L8). No method body is ever fabricated.");
  lines.push("");
  lines.push("## Known");
  lines.push(`- Kind: ${row.kind}`);
  lines.push(`- Implementing class: ${row.implClass}`);
  lines.push(`- Name evidence: ${row.nameEvidence}`);
  lines.push("- Exported @ReactMethod surface:");
  if (row.methods.length === 0) lines.push("  - (none recovered)");
  for (const m of row.methods) lines.push(`  - ${m.jsName}`);
  const constants = row.methods.map((m) => methods.get(m.nativeMethod)?.constStringReturn).filter((v): v is string => typeof v === "string");
  if (constants.length > 0) {
    lines.push("- Recovered string constants:");
    for (const c of [...new Set(constants)].sort()) lines.push(`  - ${JSON.stringify(c)}`);
  }
  lines.push("");
  lines.push("## Not known");
  lines.push("- Every method body above. hbc2js reads native signatures, annotations, and trivial const-string returns only -- it never decompiles a native method body.");
  return lines.join("\n") + "\n";
}

// --- Orchestration -------------------------------------------------------

export interface ReconstructSummary {
  /** `false` when the project directory has no native tables at all — a
   *  silent no-op (spec 27 §L8); every other field is then its empty
   *  default. */
  readonly ran: boolean;
  readonly envRecoveredCount: number;
  readonly envUnresolvedCount: number;
  readonly nativeDepsAdded: readonly string[];
  readonly firstPartyModules: readonly string[];
  readonly note: string;
}

const NO_OP_SUMMARY: ReconstructSummary = {
  ran: false,
  envRecoveredCount: 0,
  envUnresolvedCount: 0,
  nativeDepsAdded: [],
  firstPartyModules: [],
  note: "no native/ tables in the project directory; native reconstruction skipped",
};

/** spec 27 §L8: emit the native side of a rebuildable project into
 *  `outDir`, over whatever `outDir/native/*.jsonl` tables L1/L2/L4/L6 already
 *  wrote there (never re-derived from an APK here — reconstruction is a join
 *  over already-materialised facts, exactly like `seams.ts`). No-op, silently,
 *  when `outDir` holds no native tables at all. */
export function reconstructNativeProject(outDir: string): ReconstructSummary {
  if (!hasNativeTables(outDir)) return NO_OP_SUMMARY;

  const env = readNativeTable<EnvRow>(outDir, "env.jsonl");
  writeFileSync(join(outDir, ".env"), renderEnvFile(env));
  const envUnresolvedCount = env.filter((r) => r.value === "unresolved").length;

  const reactModules = readNativeTable<NativeModuleRow>(outDir, "react-modules.jsonl");
  const methodRows = readNativeTable<NativeMethodRow>(outDir, "methods.jsonl");
  const methodsByKey = new Map(methodRows.map((m) => [m.key, m] as const));

  const pkgJsonPath = join(outDir, "package.json");
  let pkgJson: Record<string, unknown> = { name: "decompiled-app", version: "0.0.0", private: true };
  if (existsSync(pkgJsonPath)) {
    try {
      pkgJson = JSON.parse(readFileSync(pkgJsonPath, "utf8")) as Record<string, unknown>;
    } catch {
      // an unreadable existing package.json is left as the default rather
      // than aborting the whole native reconstruction over it.
    }
  }
  const existingDeps = (pkgJson["dependencies"] as Record<string, string> | undefined) ?? {};
  const jsFoundPackages = new Set(Object.keys(existingDeps));
  const nativeChannel = buildNativeChannel(reactModules, jsFoundPackages);
  const mergedDeps = mergeNativeDependencies(existingDeps, nativeChannel);
  const nativeDepsAdded = nativeChannel.deps.map((d) => d.package).filter((p) => !(p in existingDeps));
  if (Object.keys(mergedDeps).length > 0) {
    writeFileSync(pkgJsonPath, JSON.stringify({ ...pkgJson, dependencies: mergedDeps }, null, 2) + "\n");
  }

  const firstPartyRows = reactModules.filter((r) => r.firstParty === true);
  const firstPartyModules: string[] = [];
  if (firstPartyRows.length > 0) mkdirSync(join(outDir, "native-todo"), { recursive: true });
  for (const row of firstPartyRows) {
    const name = moduleStubName(row);
    const dir = join(outDir, "native-todo", name);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, `${name}.java`), renderModuleStub(row, methodsByKey));
    writeFileSync(join(dir, "RESYNTHESIZE.md"), renderResynthesizeMd(row, methodsByKey));
    firstPartyModules.push(name);
  }

  const envRecoveredCount = env.length - envUnresolvedCount;
  return {
    ran: true,
    envRecoveredCount,
    envUnresolvedCount,
    nativeDepsAdded,
    firstPartyModules,
    note: `.env (${envRecoveredCount} recovered, ${envUnresolvedCount} unresolved TODO), ${nativeDepsAdded.length} native package.json dep(s), ${firstPartyModules.length} native-todo module(s)`,
  };
}
