#!/usr/bin/env bash
# tests/fixtures/build.sh — regenerate every fixture's .hbc file(s) from its source.js.
#
# Usage:
#   tests/fixtures/build.sh              # rebuild everything
#   tests/fixtures/build.sh --force      # ignore up-to-date check, recompile anyway
#
# Requires tools/get-hermesc.sh all to have been run first (tools/hermesc/v{84,94,99}/hermesc).
#
# Idempotent: a fixture's vNN.hbc is only (re)compiled if source.js is newer than it,
# or --force is given, or the .hbc is missing. Re-running with nothing changed is a no-op.
#
# Two categories of fixture are handled:
#
#   1. tests/fixtures/constructs/<name>/source.js
#        -> compiled with hermesc v84, v94, v99, each producing v84.hbc/v94.hbc/v99.hbc
#           in the same directory, UNLESS that directory has a versions.txt noting that
#           a given version is expected to fail (see "known-skip" logic below) -- in that
#           case the compile is attempted anyway (to catch the day a fetched hermesc
#           starts supporting it) but a non-zero exit is treated as an *expected*
#           skip rather than a build failure, and no stale .hbc is left behind.
#
#   2. tests/fixtures/hermes-dec-sample/source.js
#        -> special-cased. v94.hbc and v99.hbc in this directory are the ORIGINAL
#           historical fixture binaries (see licence.txt) and are never regenerated by
#           this script -- regenerating them would defeat their purpose, which is to
#           document exactly how a fresh recompile differs from them (see
#           docs/TOOLCHAIN.md). This script only (re)generates v84.hbc (no historical
#           v84 binary exists to preserve) and v99-public.hbc (the fresh-recompile
#           comparison point for the preserved v99.hbc).
#
# macOS + Linux compatible: pure bash + coreutils, no GNU-only flags.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HERMESC_DIR="$REPO_ROOT/tools/hermesc"
FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

VERSIONS="84 94 99"

built=0
skipped_uptodate=0
skipped_known=0
failed=0

# is_newer_than SRC OUT — true (0) if SRC does not exist as a compiled product yet,
# or SRC is newer than OUT, or --force. False (1) if OUT is up to date.
needs_build() {
  local src="$1" out="$2"
  [ "$FORCE" -eq 1 ] && return 0
  [ ! -f "$out" ] && return 0
  # portable "is src newer than out" without GNU stat: use find -newer.
  if [ -n "$(find "$src" -newer "$out" 2>/dev/null)" ]; then
    return 0
  fi
  return 1
}

# known_skip DIR VERSION — true (0) if this directory's versions.txt says this
# version is expected to fail.
known_skip() {
  local dir="$1" ver="$2"
  local vfile="$dir/versions.txt"
  [ -f "$vfile" ] || return 1
  grep -qE "^v${ver}: FAILS" "$vfile"
}

compile_one() {
  local src="$1" out="$2" ver="$3" dir
  dir="$(dirname "$src")"
  local hermesc="$HERMESC_DIR/v$ver/hermesc"

  if [ ! -x "$hermesc" ]; then
    echo "SKIP (no hermesc v$ver installed — run tools/get-hermesc.sh $ver): $out"
    return
  fi

  if ! needs_build "$src" "$out"; then
    skipped_uptodate=$((skipped_uptodate + 1))
    return
  fi

  # Invoke with a relative path from inside the fixture's own directory, per
  # docs/TOOLCHAIN.md's reproducibility note (debug info embeds the invoked
  # filename — always "source.js" this way, never a machine-specific absolute path).
  local out_name
  out_name="$(basename "$out")"
  if ( cd "$dir" && "$hermesc" -emit-binary -out="$out_name" source.js ) 2>/tmp/build_sh_err.$$; then
    built=$((built + 1))
    echo "OK   v$ver -> $out"
  else
    if known_skip "$dir" "$ver"; then
      skipped_known=$((skipped_known + 1))
      echo "SKIP v$ver -> $out (expected failure per $dir/versions.txt)"
      rm -f "$out" # never leave a stale/partial .hbc behind for a known-failing version
    else
      failed=$((failed + 1))
      echo "FAIL v$ver -> $out (unexpected — no versions.txt entry excuses this)"
      sed 's/^/       /' /tmp/build_sh_err.$$
    fi
  fi
  rm -f /tmp/build_sh_err.$$
}

echo "=== Building tests/fixtures/constructs/* ==="
for dir in "$REPO_ROOT"/tests/fixtures/constructs/*/; do
  dir="${dir%/}"
  src="$dir/source.js"
  [ -f "$src" ] || continue
  for ver in $VERSIONS; do
    compile_one "$src" "$dir/v$ver.hbc" "$ver"
  done
done

echo ""
echo "=== Building tests/fixtures/hermes-dec-sample (special-cased) ==="
sample_dir="$REPO_ROOT/tests/fixtures/hermes-dec-sample"
if [ -f "$sample_dir/source.js" ]; then
  echo "(v94.hbc and v99.hbc are preserved historical originals — never regenerated; see licence.txt)"
  compile_one "$sample_dir/source.js" "$sample_dir/v84.hbc" "84"
  compile_one "$sample_dir/source.js" "$sample_dir/v99-public.hbc" "99"
fi

echo ""
echo "=== Summary ==="
echo "compiled: $built   up-to-date (skipped): $skipped_uptodate   known-failure (skipped): $skipped_known   UNEXPECTED FAILURES: $failed"

if [ "$failed" -gt 0 ]; then
  echo ""
  echo "One or more fixtures failed to compile with no versions.txt excusing it — see FAIL lines above." >&2
  exit 1
fi
